spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.40-1-jdk11
    resources:
      limits:
        cpu: 512m
        memory: 2048Mi
      requests:
        cpu: 512m
        memory: 1024Mi
    workingDir: /home/jenkins/agent
  label: base
  name: base