spec:
  containers:
  - name: base
    image: jenkins/jnlp-slave:3.40-1-jdk11
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 1000m
        memory: 1024Mi
    tty: true
    securityContext:
      privileged: true
  label: base
  name: base
