spec:
  containers:
  - alwaysPullImage: true
    name: jnlp
    image: jenkins/jnlp-slave:3.40-1-jdk11
    resources:
      limits:
        cpu: 512m
        memory: 2048Mi
      requests:
        cpu: 512m
        memory: 1024Mi
  label: base
  name: base