spec:
  containers:
  - alwaysPullImage: true
    image: jenkins/jnlp-slave:3.40-1-jdk11
    name: jnlp
    resources:
      limits:
        cpu: 1000m
        memory: 2048Mi
      requests:
        cpu: 1000m
        memory: 1024Mi
  label: base
  name: base