spec:
  containers:
  - alwaysPullImage: true
    image: node
    name: node
    resources:
      limits:
        cpu: 512m
        memory: 2048Mi
      requests:
        cpu: 512m
        memory: 1024Mi
  label: base
  name: base